version: '3.9'
services:
    coupointclient:
        container_name: Coupoint-Client
        restart: always
        volumes:
            - /etc/localtime:/etc/localtime
        build:
            context: ./client
            dockerfile: Dockerfile
        expose:
            - "3000"
        networks:
            - newdocker_default
networks:
  newdocker_default:
    external: true