const companies = [
    { value: "10",  label: "Airalo" },
    { value: "9",   label: "Be שופרסל" },
    { value: "54",  label: "BuyMe" },
    { value: "2",   label: "Carrefour" },
    { value: "50",  label: "Dream Card" },
    { value: "67",  label: "Fox Home" },
    { value: "4",   label: "FreeFit" },
    { value: "1",   label: "GoodPharm" },
    { value: "12",  label: "Itay Brands" },
    { value: "44",  label: "KFC" },
    { value: "20",  label: "Laline" },
    { value: "11",  label: "Love Gift Card" },
    { value: "53",  label: "SOHO" },
    { value: "15",  label: "Victory" },
    { value: "13",  label: "Wolt" },
    { value: "63",  label: "XTRA" },
    { value: "55",  label: "א.ל.מ." },
    { value: "22",  label: "ארקיע" },
    { value: "38",  label: "ארקפה" },
    { value: "45",  label: "בורגראנץ׳" },
    { value: "46",  label: "בורגר קינג" },
    { value: "59",  label: "ביחד בשבילך" },
    { value: "41",  label: "בן אנד ג׳ריס" },
    { value: "47",  label: "בנדיקט" },
    { value: "40",  label: "גולדה" },
    { value: "42",  label: "דומינוס פיצה" },
    { value: "33",  label: "הוט סינמה" },
    { value: "7",   label: "המלביה" },
    { value: "6",   label: "ויקטורי" },
    { value: "35",  label: "יס פלאנט" },
    { value: "39",  label: "לג׳נדה" },
    { value: "56",  label: "לה שוק" },
    { value: "51",  label: "מאפה נאמן" },
    { value: "52",  label: "מגה ספורט" },
    { value: "31",  label: "מובילנד" },
    { value: "68",  label: "מחסני חשמל" },
    { value: "14",  label: "מיקי שמו" },
    { value: "58",  label: "מפעל הפיס כללי" },
    { value: "57",  label: "מפעל הפיס מקומי" },
    { value: "16",  label: "מקדונלדס" },
    { value: "64",  label: "משלוחה" },
    { value: "60",  label: "נופשונית פלוס" },
    { value: "34",  label: "סינמה סיטי" },
    { value: "30",  label: "סינמטק תל אביב" },
    { value: "28",  label: "פאפא ג׳ונס" },
    { value: "65",  label: "פולגת" },
    { value: "43",  label: "פיצה האט" },
    { value: "49",  label: "פנדורה" },
    { value: "29",  label: "פעלטון" },
    { value: "18",  label: "קפה עלית" },
    { value: "37",  label: "קפה קפה" },
    { value: "8",   label: "קרפור" },
    { value: "32",  label: "רב חן" },
    { value: "3",   label: "רולדין" },
    { value: "36",  label: "ריבר" },
    { value: "5",   label: "רמי לוי" },
    { value: "62",  label: "שובר מסעדות" },
    { value: "61",  label: "תו פלוס" },
    { value: "other", label: "אחר" }
  ];

module.exports = {companies};